app_home:
  pattern: /
  defaults: { _controller: ProdeMundialCoreBundle:Default:index }

predictions:
  pattern: /my/predictions
  defaults:
    _controller: ProdeMundialCoreBundle:Predictions:myPredictions
    _format: html

standings:
  pattern: /users/standings
  defaults:
    _controller: ProdeMundialCoreBundle:Standings:index
    _format: html

results:
  prefix: /results
  resource: @ProdeMundialWebBundle/Resources/config/routing/results.yml
  defaults:
      _format: html

payments:
  prefix: /payments
  resource: @ProdeMundialWebBundle/Resources/config/routing/payments.yml

# predictions API
api_predictions:
  prefix: /predictions
  resource: @ProdeMundialWebBundle/Resources/config/routing/predictions.yml
  defaults:
      _format: json

# standings API
api_standings:
  prefix: /standings
  resource: @ProdeMundialWebBundle/Resources/config/routing/standings.yml
  defaults:
      _format: json

api_games:
  prefix: /game
  resource: @ProdeMundialWebBundle/Resources/config/routing/game.yml
  defaults:
      _format: json