<?php

namespace ProdeMundial\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findNextGames($limit = 5, $date = null)
    {
        $date = ($date) ?: new \DateTime();

        $query = $this->createQueryBuilder('g')
            ->andWhere('g.date >= :date')
            ->orderBy('g.date', 'ASC')
            ->setParameter('date', $date)
            ->setMaxResults($limit)
        ;

        return $query->getQuery()->getResult();

    }

    public function findRecentGames($limit = 5, $date = null)
    {
        $date = ($date) ?: new \DateTime();

        $query = $this->createQueryBuilder('g')
            ->andWhere('g.date <= :date')
            ->orderBy('g.date', 'DESC')
            ->setParameter('date', $date)
            ->setMaxResults($limit)
        ;

        return $query->getQuery()->getResult();

    }
}
