<?php

namespace ProdeMundial\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PredictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredictionRepository extends EntityRepository
{
}
