ProdeMundial\CoreBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: ProdeMundial\CoreBundle\Entity\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        awayGoals:
            type: integer
            column: away_goals
            nullable: true
        homeGoals:
            type: integer
            column: home_goals
            nullable: true
        prodeResult:
            type: string
            length: '1'
            column: prode_result
            nullable: true
    manyToOne:
        group:
            targetEntity: ProdeMundial\CoreBundle\Entity\TeamsGroup
            inversedBy: games
        homeTeam:
            column: home_team
            targetEntity: ProdeMundial\CoreBundle\Entity\Team
        awayTeam:
            column: away_team
            targetEntity: ProdeMundial\CoreBundle\Entity\Team
    lifecycleCallbacks: {  }
