ProdeMundial\CoreBundle\Entity\TeamsGroup:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        slug:
            type: string
            length: 128
            gedmo:
              slug:
                style: camel
                separator: -
                fields:
                  - name
    oneToMany:
        games:
            targetEntity: ProdeMundial\CoreBundle\Entity\Game
            mappedBy: group
            cascade: ["all"]
    lifecycleCallbacks: {  }
